[build]
  publish = "public" # Change "public" to your HTML folder if different
  command = ""       # No build command needed for plain HTML

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
